SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(PRICE*SALES) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR A ON B.AUTHOR_ID=A.AUTHOR_ID
            JOIN BOOK_SALES BS ON B.BOOK_ID=BS.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC;