SELECT T.ANIMAL_ID, T.NAME
FROM (
    SELECT O.ANIMAL_ID, O.NAME
    FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
    ON I.ANIMAL_ID = O.ANIMAL_ID
    ORDER BY DATEDIFF(O.DATETIME,I.DATETIME) DESC 
    LIMIT 2) T;