WITH RENTAL_HISTORY AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
)
SELECT DISTINCT R.CAR_ID, R.CAR_TYPE, FLOOR((R.DAILY_FEE-R.DAILY_FEE*P.DISCOUNT_RATE/100)*30) AS FEE
FROM RENTAL_HISTORY R
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON R.CAR_TYPE = P.CAR_TYPE
WHERE R.CAR_TYPE IN ('세단','SUV')
    AND P.DURATION_TYPE = '30일 이상'
    AND (R.DAILY_FEE-R.DAILY_FEE*P.DISCOUNT_RATE/100)*30 >= 500000 AND (R.DAILY_FEE-R.DAILY_FEE*P.DISCOUNT_RATE/100)*30 < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID;