SELECT C.CAR_ID, C.CAR_TYPE, FLOOR((DAILY_FEE - (DAILY_FEE*(DISCOUNT_RATE/100)))*30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단','SUV')
AND C.CAR_ID NOT IN (
    SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    # WHERE START_DATE >= '2022-11-01' AND END_DATE <= '2022-11-30'
    WHERE END_DATE >= '2022-11-01' AND START_DATE <= '2022-11-30'
)
AND DURATION_TYPE = '30일 이상' AND (DAILY_FEE - (DAILY_FEE*(DISCOUNT_RATE/100)))*30 BETWEEN 500000 AND 1999999
GROUP BY C.CAR_ID, C.CAR_TYPE
ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;