SELECT USER_ID, NICKNAME, 
       CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', 
              COALESCE(STREET_ADDRESS2, '')) AS 전체주소, 
       CONCAT(SUBSTRING(TLNO,1,3), '-', SUBSTRING(TLNO,4,4), '-', SUBSTRING(TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER U JOIN
    (SELECT WRITER_ID 
        FROM USED_GOODS_BOARD 
        GROUP BY WRITER_ID 
        HAVING COUNT(BOARD_ID) >= 3
    ) B ON U.USER_ID = B.WRITER_ID
ORDER BY USER_ID DESC;