SELECT H.HISTORY_ID,
       FLOOR(C.DAILY_FEE * 
             (DATEDIFF(H.END_DATE, H.START_DATE) + 1) *
             (1 - COALESCE(
                 CASE 
                     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN DP.DISCOUNT_RATE / 100
                     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN DP.DISCOUNT_RATE / 100
                     WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN DP.DISCOUNT_RATE / 100
                     ELSE 0
                 END, 0)
             )
       ) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP 
       ON C.CAR_TYPE = DP.CAR_TYPE
      AND (
             (DP.DURATION_TYPE = '90일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90) OR
             (DP.DURATION_TYPE = '30일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90) OR
             (DP.DURATION_TYPE = '7일 이상' AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 AND DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30)
          )
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;
