WITH RECURSIVE NUMBERS(NUM) AS (
    SELECT 0
    UNION ALL
    SELECT NUM + 1
    FROM NUMBERS
    WHERE NUM < 23
)
SELECT N.NUM AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM NUMBERS N LEFT JOIN ANIMAL_OUTS A
ON N.NUM = HOUR(A.DATETIME)
GROUP BY N.NUM
ORDER BY N.NUM;