WITH CTE AS (
    SELECT EMP_NO, SUM(SCORE)/2 AS TOTAL_SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)
SELECT HE.EMP_NO, HE.EMP_NAME,
( CASE WHEN TOTAL_SCORE >= 96 THEN 'S'
         WHEN TOTAL_SCORE >= 90 THEN 'A'
         WHEN TOTAL_SCORE >= 80 THEN 'B'
         ELSE 'C' END
) AS GRADE,
( CASE WHEN TOTAL_SCORE >= 96 THEN HE.SAL*0.2
         WHEN TOTAL_SCORE >= 90 THEN HE.SAL*0.15
         WHEN TOTAL_SCORE >= 80 THEN HE.SAL*0.1
         ELSE 0 END
) AS BONUS
FROM HR_EMPLOYEES HE JOIN CTE 
ON HE.EMP_NO = CTE.EMP_NO
ORDER BY HE.EMP_NO;
