-- 코드를 작성해주세요
SELECT I.ID AS ID, N.FISH_NAME AS FISH_NAME, I.LENGTH AS LENGTH
FROM FISH_INFO I 
JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
JOIN (
    SELECT I.FISH_TYPE, MAX(LENGTH) AS MAX_LEN
    FROM FISH_INFO I
    GROUP BY I.FISH_TYPE
) AS L
ON L.FISH_TYPE = I.FISH_TYPE AND L.MAX_LEN = I.LENGTH
ORDER BY I.ID ASC;
