SELECT 
    FP.CATEGORY, 
    FP.PRICE AS MAX_PRICE, 
    FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
  AND FP.PRICE = (
      SELECT MAX(FP2.PRICE)
      FROM FOOD_PRODUCT FP2
      WHERE FP2.CATEGORY = FP.CATEGORY
  )
ORDER BY FP.PRICE DESC;
